### ISSUE TITLE
how to

### ISSUE THREAD

**Issue by namtxs** [rhildred/cors-proxy2#1]
how to use ?

**Comment by rhildred** [comment]
Hi:

I made this repo when I was wrestling with getting a corsProxy working with Cloudflare functions. Since I didn't delete it when the approach in this repo failed, I will update it with the working code in an hour or so.

Rich

**Comment by rhildred** [comment]
I think that I have cleaned up now. Please test my instructions and let me know by closing the issue if you could get it to work.

**Comment by namtxs** [comment]
can i run this code use express JS ?
i'm confused about cloudflare pages

**Comment by rhildred** [comment]
The response is handled a little differently in express. I added a method so that cors-proxy2 can run on express or on Cloudflare pages functions. Please let me know if I have answered your question.

**Comment by namtxs** [comment]
Cannot GET /

did you have telegram or discord  ?

**Comment by namtxs** [comment]
http://127.0.0.1:8080/corsproxy/google.com

302 Moved
The document has moved [here](https://www.google.com/sorry/index?continue=https://google.com/&q=EhAkBADAWhAAAAAAAAALgbi3GJyliqQGIilXXk4qPi-vMowfhc2A8DK31Ns_oufoNfKHtxSQliYTlTrCsvS0OAfYkzIBcloBQw).


how to follow redirect and display the html page

**Comment by rhildred** [comment]
Hi:

Looks like you have it working. I guess I could follow the redirect by looking at the status code and re-doing the fetch. I could use that behavior for downloading .zips from github in a progressive web app.

I refactored cors-proxy because I found the testing server supplied with isomorphic git unreliable. I wanted to use git from within a progressive web app and on stackblitz. I reasoned that if I exported it as a Cloudflare pages function I could use it as part of my larger project [diy-pwa](https://github.com/diy-pwa/diy-pwa) and it would stand up when sales engineers (my target market) start really using diy-pwa.

I didn't intend for it to be an open proxy, but I left out the code from cors-proxy that restricted it to git. My intention was to put the git code back in but I didn't think that anyone would be interested in cors-proxy2 by itself and there were more pressing details. I would be interested to know about your use case for cors-proxy2. In the meantime, I will transparently follow the redirect when fetching for the downloading a .zip from github case.

Thanks

Rich (rhildred#3087 on Discord)

**Comment by rhildred** [comment]
I created the library to run cloudflare workers and pages functions on express. It is at https://github.com/diy-pwa/cloudflare2express. I didn't write any tests yet, but if you look at the example there are 3 desk check test endpoints. I didn't get following a redirect done. Out of time for today but I am planning on cleaning up sometime soon.
